### ISSUE TITLE
Doesn't work with Neovim

### ISSUE THREAD

**Issue by mcepl** [AndrewRadev/gnugo.vim#2]
When running ``:Gnugo`` in neovim (from the HEAD of the repo), I get this error:
```
Error detected while processing function <SNR>52_Gnugo[9]..gnugo#Init[20]..gnugo#runner#Sta
rt:
line    3:
E117: Unknown function: job_start
E15: Invalid expression: job_start('gnugo '.commandline_args.' --mode gtp', { 'out_cb': fun
ction(self.HandleOutput), 'err_cb': function(self.HandleError), })
line    7:
E117: Unknown function: job_info
E15: Invalid expression: job_info(self.job).channel
Error detected while processing function <SNR>52_Gnugo[9]..gnugo#Init[21]..gnugo#runner#Red
raw:
line    1:
E117: Unknown function: ch_sendraw
```
I know that ``job`` implementation on vim8 is different from the Neovim one. Do you have any idea how complicated it would be to port your plugin to support both?

**Comment by AndrewRadev** [comment]
@mcepl I've opened a PR based on your initial commit -- it seems to work with both Vim and Neovim now: https://github.com/AndrewRadev/gnugo.vim/pull/5. But I'd appreciate if you could test it yourself and let me know if you find any issues.
